import type { BadgeProps } from "@forgecy/ui";
import type { ContentStatus, ContentVersionOrigin } from "@forgecy/core";

export const statusVariant: Record<ContentStatus, NonNullable<BadgeProps["variant"]>> = {
  draft: "neutral",
  in_review: "warning",
  changes_requested: "error",
  approved: "success",
  exported: "success",
  archived: "neutral",
};

export const versionOriginLabels: Record<ContentVersionOrigin, string> = {
  ai: "Generated by AI",
  manual: "Saved manually",
  restore: "Restore",
  submit: "Submitted for review",
};

export const outlineOriginLabels = {
  ai: "Copywriter",
  manual: "Manual edit",
  restore: "Restore",
} as const;

const jobLabels: Record<string, string> = {
  "content.generate_outline": "Generating the outline",
  "content.generate_slides": "Generating the slides",
  "content.edit_slide": "Editing a slide",
  "content.generate_image": "Generating the images",
  "content.export": "Export",
};
export const jobLabel = (kind: string) => jobLabels[kind] ?? "Job in progress";

/** Short name of the storage file kinds of an export. */
export const outputLabels = { png: "PNG", pdf: "PDF", zip: "ZIP" } as const;
